name: Data Product Deploy - dev
on:
  push:
    branches:
    - main
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
permissions:


  contents: read   # Allow the job to read repository contents
jobs:
  generate-and-deploy:
    name: "Data Product Deploy - dev"
    runs-on: ubuntu-latest
    environment: dev
    env:
      DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
      DATABRICKS_BUNDLE_ENV: ${{ vars.ENVIRONMENT_NAME }}
      DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_SP_CLIENT_ID }}
      DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_SP_CLIENT_SECRET }}
      PRODUCT_NAME: SDP
      BUNDLE_VAR_repository: https://github.com/${{ github.repository }}
      BUNDLE_VAR_git_ref_name: https://github.com/${{ github.ref_name }}
    steps:
      - name: Show git information 💡
        run: |
         echo "event_name: ${{ github.event_name }}"
         echo "ref: ${{ github.ref }}"
         echo "ref_type: ${{ github.ref_type }}"
         echo "ref_name: ${{ github.ref_name }}"
         echo "github.event.pull_request.base.ref: ${{ github.event.pull_request.base.ref }}"
      - name: Debug Environment Variables
        run: printenv | grep DATABRICKS
      - name: Checkout Repo 💻
        uses: actions/checkout@v4

      - name: Set up Databricks CLI 🧱
        uses: databricks/setup-cli@main
      - name: Set up Python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      - name: Install pip dependencies 💾
        run: |
          pip install -r requirements.txt
      - name: Block DAB permissions assignment
        run: |
          python scripts/check_no_permissions_in_dab.py
      
      - name: Display directory contents 📂
        run: |
          ls -R
      - name: Deploy Databricks Bundle 🚀
        run: databricks bundle deploy --auto-approve
        working-directory: .
      - name: Run Pipeline 🏃‍➡️
        run: |

          databricks bundle run deploy_job
        working-directory: .
      
      